export enum ProductSortEnum {
  RELEVANCE = 'RELEVANCE',
  DEFINED_BY_STORE_OWNER = 'DEFINED_BY_STORE_OWNER',
  ADDED_TIME_DESC = 'ADDED_TIME_DESC',
  ADDED_TIME_ASC = 'ADDED_TIME_ASC',
  NAME_DESC = 'NAME_DESC',
  PRICE_ASC = 'PRICE_ASC',
  PRICE_DESC = 'PRICE_DESC',
  UPDATED_TIME_ASC = 'UPDATED_TIME_ASC',
  UPDATED_TIME_DESC = 'UPDATED_TIME_DESC'
}
